server.port=8082

# Cassandra configuration
spring.data.cassandra.contact-points=cassandra
spring.data.cassandra.keyspace-name=redirect_keyspace
spring.data.cassandra.local-datacenter=datacenter1

# Logging
logging.level.com.example.project=DEBUG
logging.level.org.springframework.data.cassandra=INFO